# -*- coding: utf-8 -*-
"""dados.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NXNoqO5gWC3wFn3EYms1KAxyaIqlEO-

Rafael Franco Lourençon
"""

palavras = ["BARRIL", "CHURROS", "QUICO", "VIZINHANCA", "SEU MADRUGA"]

dicas = {
    "BARRIL": "Onde o personagem principal costuma se esconder.",
    "CHURROS": "Doce que o Chaves sempre tenta conseguir.",
    "QUICO": "Personagem mimado.",
    "VIZINHANCA": "Lugar onde todos moram.",
    "SEU MADRUGA": "Vive devendo aluguel."
}